name: Flutter CI Test, Build and Release apk

on: [push]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
    - run: flutter pub get
    - run: flutter build apk --debug --split-per-abi
    - name: Upload debugAPK
      uses: actions/upload-artifact@v2
      with:
        name: DebugAPK
        path: build/app/outputs/apk/debug/
      
#    - run: flutter build apk --release
#    - name: Upload releaseAPK
#      uses: actions/upload-artifact@v1
#      with:
#        name: DebugAPK
#        path: build/app/outputs/apk/release/

#    - run: flutter test

#    - name: Create a Release APK
#      uses: ncipollo/release-action@v1
#      with:
#        artifacts: "build/app/outputs/apk/debug/*.apk"
#        token: ${{ secrets.TOKEN }}
